apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: nikolinmajmari/{{ .Values.image }}:{{ .Values.version }}
          env:
            - name: ODOO_CMD_ARGS
              value: ""
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: "odoo"
            - name: POSTGRES_PASSWORD
              value: "odoo"
            - name: HOST
              value: "postgres"
          ports:
            - containerPort: 8069
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: saas-1
spec:
  selector:
    app: {{ .Values.name }} 
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069